# Default values for Ruby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  registry: docker.io
  org: library
  name: ruby
  tag: onbuild
  pullPolicy: IfNotPresent
service:
  name: ruby
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 900m
    memory: 768Mi
  requests:
    cpu: 450m
    memory: 256Mi
